### ISSUE TITLE
file path problem

### ISSUE THREAD

**Issue by tilllt** [cdowdy/bolt-html5-video#4]
Hi,

i cannot get the extension to work. Whatever i do, 
- uploading through the records upload function and using "filelist" in datatype 
- uploading through bolts file upload and using "file" in datatype

the extension ends up adding a video block with a path like this:
`<source src="//files.mp4" type="video/mp4">`
(and webm respectively).

this is unrelated to the way the file is uploaded, the extension simply does not seem to reference the filename correctly. or - very probably - i am doing something wrong.

in any case, help would be appreciated.

**Comment by cdowdy** [comment]
Hey @

**Comment by cdowdy** [comment]
Whoops on my phone and accidentally hit "close" when I tried to scroll haha 😀


Anywho! Can I get a copy of your contenttype ? Also what version of bolt and the extension do you have? Sorry about the problems hopefully I can get this situated!


If I don't get back to you today I'll definitely be able to tomorrow

**Comment by tilllt** [comment]
sure, so my idea was to have a "container" video contenttype, that basically only has a title and videos (and stills) ... for my purpose i dont need "text" or "html" content connected to the videos, so here we go:

```
videos:
  name: Videos
  singular_name: Video
  fields:
    # other fields here
    # video: # our video field to call in the template
    #    type: file # the type of field we are using.
    title:
            type: text
    slug:
            type: slug
            uses: [ title ]
    video:
            type: filelist
```
